server:
  port: 0 # random port

spring:
  application:
    name: shop-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: default       # 사용할 프로파일
  cloud:
    config:
      fail-fast: true
#  datasource:
#    # Postgres 서버 타임존을 서울(KST)로 맞추기 위해 옵션 추가
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/test?currentSchema=public&options=-c%20TimeZone=Asia/Seoul}
#    driver-class-name: org.postgresql.Driver
#    username: ${SPRING_DATASOURCE_USERNAME:postgres}
#    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
#  jackson:
#    time-zone: Asia/Seoul
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        jdbc:
#          time_zone: Asia/Seoul
#  batch:
#    jdbc:
#      initialize-schema: never
#  task:
#    scheduling:
#      cron:
#        settlement: ${SETTLEMENT_CRON:-}  # 매일 00:00 실행 기본값

# config server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, prometheus

#api:
#  v1: /api/v1
#settlement:
#  async:
#    enabled: ${SETTLEMENT_ASYNC:false}          # Config 서버에서 덮어쓰지 못하면 기본값 사용
#    pool-size: ${SETTLEMENT_ASYNC_POOL_SIZE:5}

#payment:
#  toss:
#    secret-key: ${TOSS_SECRET_KEY:test_sk_yZqmkKeP8gJEZ9Wl4dBOrbQRxB9l}
#    success-url: ${TOSS_SUCCESS_URL:http://localhost:8080/payments/success.html}
#    fail-url: ${TOSS_FAIL_URL:http://localhost:8080/payments/fail.html}
kafka:
  # 로컬 도커 브로커 포트
  bootstrap-servers: localhost:29092
  topic:
    # 주문 이벤트를 주고받는 토픽 이름
    async-orders: shop.async-orders.v1
  consumer:
    # 샘플 컨슈머 그룹
    group-id: shop-async-consumer
